apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glowing-spoon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/amossg/glowing-spoon.git'
    targetRevision: HEAD
    path: .
    plugin: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

