apiVersion: apps/v1
kind: Deployment
metadata:
  name: glowing-spoon
  namespace: test-argocd 
  labels:
    app: glowing-spoon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glowing-spoon
  template:
    metadata:
      labels:
        app: glowing-spoon
    spec:
      containers:
      - name: glowing-spoon
        image: nginx:latest
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: glowing-spoon-secret
              key: username
        volumeMounts:
        - name: avp
          mountPath: /home/argocd/cmp-server/plugins
      volumes:
      - name: avp
        emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: glowing-spoon-secret
  namespace: test-argocd 
  annotations:
    avp.kubernetes.io/path: "glowing-spoon/config"
type: Opaque
data:
  username: "<username>"

